### ISSUE TITLE
Вопрос про исходный код релиза

### ISSUE THREAD

**Issue by webomax** [telefon1c/MikoPBX#1]
Добрый день. По вышедшим релизам исходный код не сразу пушите в репозитарий?
Например по этому Release MikoPBX 2019.4.53 еще нет исходного кода.

**Comment by jorikfon** [comment]
Да, пока только релизы пушим. Между релизами 2019.4.53 и предыдущим нет разницы в коде, там разница в параметрах сборки всей машины.
